version: "3.8"
services:
  mymongo:
    image: mongo:4.4.4
    container_name: mymongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db   
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # env_file: "./.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongonetwork 
  
  chess-board-app:
    image: "node:12-slim"
    container_name: chess-board-app
    working_dir: /home/node/app
    env_file: './.env'
    ports:
      - ${CHESS_BOARD_PORT}:4001
    volumes:
      - ../chess-game-backend:/home/node/app
    command: npm start  
    networks:
      - mongonetwork 

networks:
  mongonetwork:     